version: '3.9'
services:
  postgres:
    image: postgis/postgis
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DATABASE: postgis
      POSTGRES_USER: postgis
      POSTGRES_PASSWORD: postgis
    ports:
      - 5432:5432
    volumes:
      - ~/pgdata:/var/lib/postgresql/data
